export const USER_DETAIL = 'USER_DETAIL';
export const REMEMBER_ME = 'REMEMBER_ME';
export const AUTH_TOKEN = 'AUTH_TOKEN';
export const RESET_STORE = 'RESET_STORE';
export const MEMBER_DETAIL = 'MEMBER_DETAIL';
export const MEMBER_DATA = 'MEMBER_DATA';
export const FILTER_DATA = 'FILTER_DATA';
export const SEARCH_DATA = 'SEARCH_DATA';
export const CAN_CALL_DIRECTOY_API = 'CAN_CALL_DIRECTOY_API';
export const LOADING = 'LOADING';
export const NOTIFICATION_DETAIL = 'NOTIFICATION_DETAIL';
export const NOTIFICATION_TYPE = 'NOTIFICATION_TYPE';
export const NOTIFICATION_LISTENER_FLAG = 'NOTIFICATION_LISTENER_FLAG';
export const EVENT_INFORMATION = 'EVENT_INFORMATION';
export const NOTIFICATION_ARRAY_FOR_POP_UP = 'NOTIFICATION_ARRAY_FOR_POP_UP';
export const FETCH_SHOP_LIST = 'FETCH_SHOP_LIST';
export const FETCH_RECENT_ITEMS = 'FETCH_RECENT_ITEMS';
export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const FETCH_MY_CART = 'FETCH_MY_CART';
export const FETCH_MY_ADDRESS = 'FETCH_MY_ADDRESS';
export const FETCH_CUSTOMER_ORDER = 'FETCH_CUSTOMER_ORDER';
export const FETCH_SHOP_PRODUCT = 'FETCH_SHOP_PRODUCT';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_ALL_SHOPS_FOR_CUSTOMER = 'FETCH_ALL_SHOPS_FOR_CUSTOMER';
export const FETCH_ALL_TRENDING_PRODUCT = 'FETCH_ALL_TRENDING_PRODUCT';
export const FETCH_SHOP_OWNER_ORDERS = 'FETCH_SHOP_OWNER_ORDERS';









